// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xooipialptqtdfymdkqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb2lwaWFscHRxdGRmeW1ka3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDQ2NTAsImV4cCI6MjA2NjkyMDY1MH0.UXDRfjzr3AgUmhZqKV3SptwrW38SvW72RLFRTwQf48k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});